actor_input_emb1: 8
actor_input_emb2: 13
actor_d_model: 6
actor_d_k: 5
actor_mlp_hidden_layers: [24, 18, 12, 6]
critic_input_emb1: 8
critic_input_emb2: 13
critic_d_model: 6
critic_d_k: 5
critic_mlp_hidden_layers: [24, 18, 12, 6, 1]
num_episodes: 100_000  # number of episodes to train
gamma: 0.99  # discount factor
lr: 0.001  # learning rate
entropy_penalty: 0.001 # entropy penalty
save_path: "./models/a2c_transformer"  # path to save the model files
render: False  # setting it to True would render after every "render_freq" episodes
render_freq: 500  # if render is True, the episode will be rendered after every render_freq episodes
save_freq: 500  # model would be saved after every save_freq epsidoes
