input_dim : 67
self_state_dim : 6
mlp1_dims : [150, 100]
mlp2_dims : [100, 50]
mlp3_dims : [150, 100, 100, 1]
attention_dims : [100, 100, 1]
with_global_state : True
cell_size : 1
cell_num : 4
om_channel_size : 3
buffer_size : 100_000
epsilon_start: 0.5
epsilon_end: 0.1
epsilon_decay: 4000
gamma : 0.9
num_episodes : 50_000
k : 1
lr : 0.001
num_batches : 100
batch_size : 100
target_update_interval : 50
render : False
render_freq : 500
save_path : "./models/crowdnav"
save_freq : 500
il_episodes : 3000